version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /services/portainer/data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - portainer
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:9443 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=portainer"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.bspwr.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.middlewares=local-allowlist@file"

networks:
  portainer:
    name: portainer
    external: true